FROM golang:1.22 AS builder

WORKDIR /app
COPY . .

RUN go mod tidy
RUN go build -o coordinator ./cmd/coordinator

FROM debian:bookworm-slim
WORKDIR /root/
COPY --from=builder /app/coordinator .

CMD ["./coordinator"]
