FROM golang:1.22 AS builder

WORKDIR /app
COPY . .

RUN go mod tidy
RUN go build -o gateway ./cmd/gateway

FROM debian:bookworm-slim
WORKDIR /root/

COPY --from=builder /app/gateway .
COPY --from=builder /app/ui ./ui

EXPOSE 8080
CMD ["./gateway"]
