FROM golang:1.22 AS builder

WORKDIR /app
COPY . .

RUN go mod tidy
RUN go build -o zone-server ./cmd/zone-server

FROM debian:bookworm-slim
WORKDIR /root/
COPY --from=builder /app/zone-server .

EXPOSE 50051
CMD ["./zone-server"]
