// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/world.proto

package worldpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_world_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_proto_world_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *JoinRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *JoinRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_proto_world_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_proto_rawDescGZIP(), []int{3}
}

func (x *JoinResponse) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *JoinResponse) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Dx            int32                  `protobuf:"varint,2,opt,name=dx,proto3" json:"dx,omitempty"`
	Dy            int32                  `protobuf:"varint,3,opt,name=dy,proto3" json:"dy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_proto_world_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_proto_rawDescGZIP(), []int{4}
}

func (x *MoveRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MoveRequest) GetDx() int32 {
	if x != nil {
		return x.Dx
	}
	return 0
}

func (x *MoveRequest) GetDy() int32 {
	if x != nil {
		return x.Dy
	}
	return 0
}

type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_proto_world_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_proto_rawDescGZIP(), []int{5}
}

func (x *MoveResponse) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveResponse) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_proto_world_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_proto_rawDescGZIP(), []int{6}
}

func (x *GetStateRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_proto_world_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_proto_rawDescGZIP(), []int{7}
}

func (x *GetStateResponse) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *GetStateResponse) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	MinX          int32                  `protobuf:"varint,2,opt,name=min_x,json=minX,proto3" json:"min_x,omitempty"`
	MaxX          int32                  `protobuf:"varint,3,opt,name=max_x,json=maxX,proto3" json:"max_x,omitempty"`
	MinY          int32                  `protobuf:"varint,4,opt,name=min_y,json=minY,proto3" json:"min_y,omitempty"`
	MaxY          int32                  `protobuf:"varint,5,opt,name=max_y,json=maxY,proto3" json:"max_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_world_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_proto_rawDescGZIP(), []int{8}
}

func (x *StreamRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *StreamRequest) GetMinX() int32 {
	if x != nil {
		return x.MinX
	}
	return 0
}

func (x *StreamRequest) GetMaxX() int32 {
	if x != nil {
		return x.MaxX
	}
	return 0
}

func (x *StreamRequest) GetMinY() int32 {
	if x != nil {
		return x.MinY
	}
	return 0
}

func (x *StreamRequest) GetMaxY() int32 {
	if x != nil {
		return x.MaxY
	}
	return 0
}

type ZoneUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneUpdate) Reset() {
	*x = ZoneUpdate{}
	mi := &file_proto_world_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneUpdate) ProtoMessage() {}

func (x *ZoneUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneUpdate.ProtoReflect.Descriptor instead.
func (*ZoneUpdate) Descriptor() ([]byte, []int) {
	return file_proto_world_proto_rawDescGZIP(), []int{9}
}

func (x *ZoneUpdate) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ZoneUpdate) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ZoneUpdate) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_proto_world_proto protoreflect.FileDescriptor

const file_proto_world_proto_rawDesc = "" +
	"\n" +
	"\x11proto/world.proto\x12\x05world\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"F\n" +
	"\vJoinRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"*\n" +
	"\fJoinResponse\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"J\n" +
	"\vMoveRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x0e\n" +
	"\x02dx\x18\x02 \x01(\x05R\x02dx\x12\x0e\n" +
	"\x02dy\x18\x03 \x01(\x05R\x02dy\"*\n" +
	"\fMoveResponse\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\".\n" +
	"\x0fGetStateRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\".\n" +
	"\x10GetStateResponse\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"|\n" +
	"\rStreamRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12\x13\n" +
	"\x05min_x\x18\x02 \x01(\x05R\x04minX\x12\x13\n" +
	"\x05max_x\x18\x03 \x01(\x05R\x04maxX\x12\x13\n" +
	"\x05min_y\x18\x04 \x01(\x05R\x04minY\x12\x13\n" +
	"\x05max_y\x18\x05 \x01(\x05R\x04maxY\"E\n" +
	"\n" +
	"ZoneUpdate\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y2\x9d\x02\n" +
	"\vZoneService\x12/\n" +
	"\x04Ping\x12\x12.world.PingRequest\x1a\x13.world.PingResponse\x12/\n" +
	"\x04Join\x12\x12.world.JoinRequest\x1a\x13.world.JoinResponse\x12/\n" +
	"\x04Move\x12\x12.world.MoveRequest\x1a\x13.world.MoveResponse\x12;\n" +
	"\bGetState\x12\x16.world.GetStateRequest\x1a\x17.world.GetStateResponse\x12>\n" +
	"\x11StreamZoneUpdates\x12\x14.world.StreamRequest\x1a\x11.world.ZoneUpdate0\x01B\x1aZ\x18shardworld/proto/worldpbb\x06proto3"

var (
	file_proto_world_proto_rawDescOnce sync.Once
	file_proto_world_proto_rawDescData []byte
)

func file_proto_world_proto_rawDescGZIP() []byte {
	file_proto_world_proto_rawDescOnce.Do(func() {
		file_proto_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_world_proto_rawDesc), len(file_proto_world_proto_rawDesc)))
	})
	return file_proto_world_proto_rawDescData
}

var file_proto_world_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_world_proto_goTypes = []any{
	(*PingRequest)(nil),      // 0: world.PingRequest
	(*PingResponse)(nil),     // 1: world.PingResponse
	(*JoinRequest)(nil),      // 2: world.JoinRequest
	(*JoinResponse)(nil),     // 3: world.JoinResponse
	(*MoveRequest)(nil),      // 4: world.MoveRequest
	(*MoveResponse)(nil),     // 5: world.MoveResponse
	(*GetStateRequest)(nil),  // 6: world.GetStateRequest
	(*GetStateResponse)(nil), // 7: world.GetStateResponse
	(*StreamRequest)(nil),    // 8: world.StreamRequest
	(*ZoneUpdate)(nil),       // 9: world.ZoneUpdate
}
var file_proto_world_proto_depIdxs = []int32{
	0, // 0: world.ZoneService.Ping:input_type -> world.PingRequest
	2, // 1: world.ZoneService.Join:input_type -> world.JoinRequest
	4, // 2: world.ZoneService.Move:input_type -> world.MoveRequest
	6, // 3: world.ZoneService.GetState:input_type -> world.GetStateRequest
	8, // 4: world.ZoneService.StreamZoneUpdates:input_type -> world.StreamRequest
	1, // 5: world.ZoneService.Ping:output_type -> world.PingResponse
	3, // 6: world.ZoneService.Join:output_type -> world.JoinResponse
	5, // 7: world.ZoneService.Move:output_type -> world.MoveResponse
	7, // 8: world.ZoneService.GetState:output_type -> world.GetStateResponse
	9, // 9: world.ZoneService.StreamZoneUpdates:output_type -> world.ZoneUpdate
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_world_proto_init() }
func file_proto_world_proto_init() {
	if File_proto_world_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_world_proto_rawDesc), len(file_proto_world_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_world_proto_goTypes,
		DependencyIndexes: file_proto_world_proto_depIdxs,
		MessageInfos:      file_proto_world_proto_msgTypes,
	}.Build()
	File_proto_world_proto = out.File
	file_proto_world_proto_goTypes = nil
	file_proto_world_proto_depIdxs = nil
}
